# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Got < Formula
  desc "CLI tool for manipulating git branches together with Jira tickets"
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/macanton/got/releases/download/v0.0.3/got_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "ed867695495ba40af30874a56d143a552fc8d101e4879dbb7265c1f097259a55"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/macanton/got/releases/download/v0.0.3/got_0.0.3_Linux_x86_64.tar.gz"
    sha256 "278251b164619dd8887e349c5d416b86e976b00007e5d58f7bc237f409d9f3a2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/macanton/got/releases/download/v0.0.3/got_0.0.3_Linux_arm64.tar.gz"
    sha256 "3bf68e32dbbfd2b93908363cedbef849cef729af348585a55e296d2288732691"
  end

  def install
    bin.install "got"
  end
end
